# Generated by Django 3.2 on 2021-04-30 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='ルーム名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='開設日時')),
                ('password', models.CharField(blank=True, max_length=300, null=True, verbose_name='パスワード')),
            ],
            options={
                'verbose_name': 'チャットルーム',
                'verbose_name_plural': 'チャットルーム',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('has_read', models.BooleanField(default=False, verbose_name='既読')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('src', models.FileField(blank=True, null=True, upload_to='chat/%Y/%m/%d/', verbose_name='添付ファイル')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom')),
            ],
            options={
                'verbose_name': 'チャットルーム',
                'verbose_name_plural': 'チャットルーム',
            },
        ),
    ]
