# Generated by Django 3.2 on 2021-04-30 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210501_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='thread',
            new_name='room',
        ),
    ]
