# Generated by Django 3.2 on 2021-05-02 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_thread_chat_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='has_read',
        ),
    ]
